name: q2chat

services:
  frontend:
    build:
      context: frontend
      dockerfile: frontend.dockerfile
    depends_on:
      - backend
    volumes:
    - ./frontend:/usr/src/frontend
    ports:
      - "8081:8081"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: backend
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHDOG_ENABLED=true
    env_file:
      - ./backend/.env
